apiVersion: v1
kind: Secret
metadata:
  name: {{ include "php-fpm.fullname" . }}
  labels:
    app: {{ template "php-fpm.name" . }}
    chart: {{ template "php-fpm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- range $name, $value := .Values.env.secret }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
